name: google test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://rainbowaurora/ubuntu:18.04
      with:
        args: cmake .
        args: make
        args: find -name "*_test" | bash

