name: google test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run docker container
      uses: docker://rainbowaurora/ubuntu:18.04
    - name: watch /usr/local/lib
      run: ls /usr/local/lib
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make project
      run: cd build && make
    - name: run test
      run: sudo find -name "*_test"  -type f | bash
   
