name: google test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run docker container
      uses: docker://rainbowaurora/ubuntu:18.04
      run: ls /usr/local/lib
