name: google test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run docker container
      uses: docker://rainbowaurora/ubuntu:18.04
      with:
        args: 
        - ls /usr/local/lib
        - git clone https://github.com/RainBowAurora/CodeRecord.git
        - cd CodeRecord
        - mkdir build && cd build && cmake ..
        - make
        - find -name "*test" -type f | bash
   
