name: google test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://rainbowaurora/ubuntu:18.04
      with: 
        args: cmake .
    - uses: docker://rainbowaurora/ubuntu:18.04
      with: 
        args: make
    - name: run test
      run: sudo find -name "*_test"  -type f | bash
